-- C# syntax definition
lex.define_syntax({
    name       = "C#",
    extensions = { ".cs" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "break", "case", "catch", "continue", "default", "do",
        "else", "finally", "for", "foreach", "goto", "if",
        "in", "return", "switch", "throw", "try", "while",
        "await", "yield",
    },
    keywords2  = {
        "abstract", "as", "base", "checked", "class", "const",
        "delegate", "enum", "event", "explicit", "extern",
        "false", "fixed", "implicit", "interface", "internal",
        "is", "lock", "namespace", "new", "null", "object",
        "operator", "out", "override", "params", "partial",
        "private", "protected", "public", "readonly", "ref",
        "sealed", "sizeof", "stackalloc", "static", "struct",
        "this", "true", "typeof", "unchecked", "unsafe",
        "using", "virtual", "volatile", "with",
        "async", "dynamic", "record", "init", "required",
        "file", "scoped",
    },
    keywords3  = {
        "bool", "byte", "char", "decimal", "double", "float",
        "int", "long", "nint", "nuint", "sbyte", "short",
        "string", "uint", "ulong", "ushort", "var", "void",
        "Console", "String", "Math", "Array", "List", "Dictionary",
        "IEnumerable", "ICollection", "IList", "IDictionary",
        "Task", "Thread", "Action", "Func", "Exception",
        "ArgumentException", "ArgumentNullException",
        "InvalidOperationException", "NotImplementedException",
        "NullReferenceException", "IndexOutOfRangeException",
        "IOException", "KeyNotFoundException",
        "Nullable", "Span", "Memory", "ReadOnlySpan",
        "StringBuilder", "DateTime", "TimeSpan", "Guid",
    },
})
