-- CSS syntax definition
lex.define_syntax({
    name       = "CSS",
    extensions = { ".css" },
    comment    = "/*",  -- block comment only
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        -- at-rules
        "@import", "@media", "@keyframes", "@font-face",
        "@charset", "@namespace", "@supports", "@layer",
        "@page", "@counter-style", "@property",
        -- media query keywords
        "screen", "print", "all",
        "and", "or", "not", "only",
        "min-width", "max-width", "min-height", "max-height",
    },
    keywords2  = {
        -- most-used properties
        "display", "position", "top", "right", "bottom", "left",
        "width", "height", "min-width", "max-width", "min-height", "max-height",
        "margin", "margin-top", "margin-right", "margin-bottom", "margin-left",
        "padding", "padding-top", "padding-right", "padding-bottom", "padding-left",
        "border", "border-top", "border-right", "border-bottom", "border-left",
        "border-radius", "border-width", "border-style", "border-color",
        "outline", "outline-offset",
        "box-sizing", "box-shadow",
        "background", "background-color", "background-image",
        "background-size", "background-position", "background-repeat",
        "color", "opacity",
        "font", "font-size", "font-family", "font-weight", "font-style",
        "font-variant", "font-stretch", "line-height", "letter-spacing",
        "text-align", "text-decoration", "text-transform", "text-shadow",
        "text-overflow", "white-space", "word-break", "overflow-wrap",
        "vertical-align",
        "flex", "flex-direction", "flex-wrap", "flex-flow",
        "flex-grow", "flex-shrink", "flex-basis",
        "justify-content", "align-items", "align-self", "align-content",
        "gap", "row-gap", "column-gap", "order",
        "grid", "grid-template", "grid-template-columns", "grid-template-rows",
        "grid-template-areas", "grid-area", "grid-column", "grid-row",
        "grid-auto-flow", "grid-auto-columns", "grid-auto-rows",
        "overflow", "overflow-x", "overflow-y",
        "transform", "transform-origin",
        "transition", "transition-property", "transition-duration",
        "transition-timing-function", "transition-delay",
        "animation", "animation-name", "animation-duration",
        "animation-timing-function", "animation-delay",
        "animation-iteration-count", "animation-direction",
        "animation-fill-mode", "animation-play-state",
        "content", "counter-reset", "counter-increment",
        "cursor", "pointer-events", "user-select",
        "visibility", "z-index", "float", "clear",
        "list-style", "list-style-type", "list-style-position",
        "table-layout", "border-collapse", "border-spacing",
        "resize", "appearance", "clip-path", "filter", "backdrop-filter",
        "object-fit", "object-position", "aspect-ratio",
        "scroll-behavior", "scroll-snap-type", "scroll-snap-align",
        "will-change", "contain",
        "columns", "column-count", "column-width", "column-gap",
        "column-rule", "break-inside", "break-before", "break-after",
    },
    keywords3  = {
        -- values / functions
        "auto", "none", "inherit", "initial", "unset", "revert",
        "normal", "bold", "italic", "oblique",
        "block", "inline", "inline-block", "flex", "inline-flex",
        "grid", "inline-grid", "table", "list-item", "contents",
        "relative", "absolute", "fixed", "sticky", "static",
        "hidden", "visible", "scroll", "clip",
        "solid", "dashed", "dotted", "double", "groove",
        "ridge", "inset", "outset",
        "row", "column", "row-reverse", "column-reverse",
        "wrap", "nowrap", "wrap-reverse",
        "center", "start", "end", "stretch",
        "space-between", "space-around", "space-evenly",
        "baseline", "first baseline", "last baseline",
        "repeat", "no-repeat", "space", "round",
        "cover", "contain",
        "currentColor", "transparent",
        "pointer", "default", "text", "crosshair", "not-allowed", "grab",
        "linear-gradient", "radial-gradient", "conic-gradient",
        "var", "calc", "min", "max", "clamp",
        "rgb", "rgba", "hsl", "hsla", "oklch", "oklab", "color",
        "url", "format", "local",
        "translate", "rotate", "scale", "skew",
        "translateX", "translateY", "translateZ", "translate3d",
        "scaleX", "scaleY", "scaleZ", "scale3d",
        "rotateX", "rotateY", "rotateZ", "rotate3d",
        "perspective", "matrix", "matrix3d",
        "blur", "brightness", "contrast", "drop-shadow",
        "grayscale", "hue-rotate", "invert", "saturate", "sepia",
        "px", "em", "rem", "vh", "vw", "vmin", "vmax", "fr",
        "deg", "rad", "turn", "grad",
        "ms", "s",
        "ease", "ease-in", "ease-out", "ease-in-out", "linear",
        "cubic-bezier", "steps",
        "infinite", "forwards", "backwards", "both", "paused", "running",
        "fr", "ch", "ex", "cm", "mm", "in", "pt", "pc",
    },
    flags = 3,
})
