-- D syntax definition
lex.define_syntax({
    name       = "D",
    extensions = { ".d", ".di" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "break", "case", "catch", "continue", "default", "do",
        "else", "finally", "for", "foreach", "foreach_reverse",
        "goto", "if", "in", "return", "switch", "throw",
        "try", "while", "with",
    },
    keywords2  = {
        "abstract", "alias", "align", "asm", "assert",
        "auto", "body", "cast", "class", "const",
        "debug", "delegate", "delete", "deprecated",
        "enum", "export", "extern", "false", "final",
        "function", "immutable", "import", "interface",
        "invariant", "is", "lazy", "macro", "mixin",
        "module", "new", "nothrow", "null", "out",
        "override", "package", "pragma", "private",
        "protected", "public", "pure", "ref", "scope",
        "shared", "static", "struct", "super", "synchronized",
        "template", "this", "true", "typedef", "typeid",
        "typeof", "union", "unittest", "version", "void",
        "__FILE__", "__LINE__", "__MODULE__", "__FUNCTION__",
        "__gshared", "__traits", "__vector", "__parameters",
    },
    keywords3  = {
        "bool", "byte", "cdouble", "cent", "cfloat",
        "char", "creal", "dchar", "double", "float",
        "idouble", "ifloat", "int", "ireal", "long",
        "real", "short", "ubyte", "ucent", "uint",
        "ulong", "ushort", "wchar",
        "string", "wstring", "dstring",
        "size_t", "ptrdiff_t",
        "writeln", "writef", "writefln", "write",
        "readln",
        "Exception", "Error", "Throwable",
    },
})
