-- Elixir syntax definition
lex.define_syntax({
    name       = "Elixir",
    extensions = { ".ex", ".exs" },
    comment    = "#",
    keywords1  = {
        "after", "and", "case", "catch", "cond", "do",
        "else", "end", "for", "if", "in", "not",
        "or", "raise", "receive", "rescue", "throw",
        "try", "unless", "when", "with",
    },
    keywords2  = {
        "alias", "defcallback", "defdelegate", "defexception",
        "defguard", "defguardp", "defimpl", "defmacro",
        "defmacrop", "defmodule", "defoverridable",
        "defp", "defprotocol", "defstruct", "def",
        "fn", "import", "quote", "require", "unquote",
        "use",
        "true", "false", "nil",
        "__MODULE__", "__DIR__", "__CALLER__", "__ENV__",
        "__STACKTRACE__",
    },
    keywords3  = {
        "Integer", "Float", "String", "Atom", "Tuple",
        "List", "Map", "Set", "Keyword", "Range",
        "Enum", "Stream", "Flow",
        "IO", "File", "Path", "Port",
        "Process", "Task", "Agent", "GenServer",
        "Supervisor", "Application",
        "Module", "Kernel", "Code",
        "Exception", "RuntimeError", "ArgumentError",
        "inspect", "puts", "print", "gets",
        "length", "hd", "tl", "elem", "size",
        "is_nil", "is_atom", "is_binary", "is_boolean",
        "is_float", "is_function", "is_integer", "is_list",
        "is_map", "is_number", "is_pid", "is_port",
        "is_reference", "is_tuple",
    },
})
