-- Erlang syntax definition
lex.define_syntax({
    name       = "Erlang",
    extensions = { ".erl", ".hrl" },
    comment    = "%",
    keywords1  = {
        "after", "and", "andalso", "band", "begin", "bnot",
        "bor", "bsl", "bsr", "bxor", "case", "catch",
        "cond", "div", "end", "fun", "if", "let",
        "not", "of", "or", "orelse", "receive",
        "rem", "try", "when", "xor",
    },
    keywords2  = {
        -- directives
        "-module", "-export", "-import", "-compile", "-define",
        "-record", "-type", "-spec", "-behaviour", "-callback",
        "-include", "-include_lib", "-ifdef", "-ifndef",
        "-undef", "-else", "-endif", "-file",
        "true", "false",
    },
    keywords3  = {
        "abs", "apply", "atom_to_binary", "atom_to_list",
        "binary_to_atom", "binary_to_integer", "binary_to_list",
        "binary_to_term",
        "element", "setelement", "tuple_size", "tuple_to_list",
        "float", "float_to_binary", "float_to_list",
        "hd", "tl", "length", "list_to_atom", "list_to_binary",
        "list_to_integer", "list_to_tuple",
        "integer_to_binary", "integer_to_list",
        "is_atom", "is_binary", "is_boolean", "is_float",
        "is_function", "is_integer", "is_list", "is_map",
        "is_number", "is_pid", "is_port", "is_process_alive",
        "is_record", "is_reference", "is_tuple",
        "make_ref", "max", "min", "node",
        "self", "spawn", "spawn_link", "spawn_monitor",
        "send", "receive", "register", "whereis",
        "throw", "error", "exit",
        "io", "io_lib", "lists", "maps", "sets",
        "string", "binary", "erlang", "proplists",
        "ets", "dets", "mnesia",
        "gen_server", "gen_statem", "gen_event",
        "supervisor",
    },
})
