-- FASM (Flat Assembler) syntax definition
lex.define_syntax({
    name       = "FASM",
    extensions = { ".fasm", ".fas" },
    comment    = ";",
    keywords1  = {
        -- control flow
        "jmp", "je", "jne", "jz", "jnz", "jg", "jge", "jl", "jle",
        "ja", "jae", "jb", "jbe", "jo", "jno", "js", "jns",
        "jcxz", "jecxz", "jrcxz",
        "loop", "loope", "loopne",
        "call", "ret", "retn", "retf", "iret", "iretd", "iretq",
        "enter", "leave",
    },
    keywords2  = {
        -- instructions (same ISA as NASM)
        "mov", "movsx", "movzx", "movs", "movsb", "movsw", "movsd", "movsq",
        "push", "pop", "pushad", "popad", "pushf", "popf",
        "lea", "xchg", "xadd", "cmpxchg", "bswap",
        "add", "sub", "mul", "imul", "div", "idiv", "inc", "dec",
        "neg", "adc", "sbb",
        "and", "or", "xor", "not", "shl", "shr", "sal", "sar",
        "rol", "ror", "rcl", "rcr", "shld", "shrd",
        "cmp", "test", "bt", "bts", "btr", "btc", "bsf", "bsr",
        "nop", "hlt", "cli", "sti", "cld", "std", "clc", "stc", "cmc",
        "int", "syscall", "sysenter", "sysexit", "cpuid", "rdtsc",
        "rep", "repe", "repne",
        "lods", "lodsb", "lodsw", "lodsd", "lodsq",
        "stos", "stosb", "stosw", "stosd", "stosq",
        "scas", "cmpsb", "cmpsw", "cmpsd",
        "in", "out",
        "cbw", "cwd", "cwde", "cdq", "cdqe",
    },
    keywords3  = {
        -- registers
        "rax", "rbx", "rcx", "rdx", "rsi", "rdi", "rsp", "rbp",
        "r8",  "r9",  "r10", "r11", "r12", "r13", "r14", "r15",
        "eax", "ebx", "ecx", "edx", "esi", "edi", "esp", "ebp",
        "ax",  "bx",  "cx",  "dx",  "si",  "di",  "sp",  "bp",
        "al",  "bl",  "cl",  "dl",  "ah",  "bh",  "ch",  "dh",
        "cs",  "ds",  "es",  "fs",  "gs",  "ss",
        "rip", "eip",
        "xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7",
        "xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15",
        "ymm0","ymm1","ymm2","ymm3","ymm4","ymm5","ymm6","ymm7",
        "mm0", "mm1", "mm2", "mm3", "mm4", "mm5", "mm6", "mm7",
        "st0", "st1", "st2", "st3", "st4", "st5", "st6", "st7",
        -- FASM directives
        "format", "use16", "use32", "use64",
        "section", "segment", "public", "extrn",
        "db", "dw", "dd", "dq", "dt", "dqword",
        "rb", "rw", "rd", "rq", "rt",
        "org", "align", "file", "load", "store",
        "label", "virtual", "end virtual",
        "macro", "end macro", "local", "common", "forward", "reverse",
        "if", "else", "end if", "repeat", "end repeat",
        "while", "end while", "iterate", "end iterate",
        "match", "struc", "ends", "namespace", "end namespace",
        "define", "include",
        "byte", "word", "dword", "qword", "tword",
        "at", "dup",
        "EAX_", "EBX_",
    },
})
