-- Fortran syntax definition
lex.define_syntax({
    name       = "Fortran",
    extensions = { ".f", ".f90", ".f95", ".f03", ".f08", ".f18", ".for", ".fpp" },
    comment    = "!",
    keywords1  = {
        "if", "else", "elseif", "end", "then",
        "do", "while", "forall", "where", "elsewhere",
        "select", "case", "default",
        "exit", "cycle", "return", "stop", "error stop",
        "go", "goto",
    },
    keywords2  = {
        "program", "module", "submodule", "block", "associate",
        "subroutine", "function", "contains",
        "use", "only", "import",
        "implicit", "none", "explicit",
        "integer", "real", "complex", "logical", "character",
        "type", "class", "enum", "enumerator",
        "common", "data", "block", "equivalence",
        "parameter", "dimension", "allocatable", "pointer", "target",
        "intent", "in", "out", "inout",
        "optional", "value", "save", "volatile",
        "public", "private", "protected",
        "abstract", "deferred", "final",
        "procedure", "interface", "operator", "assignment",
        "generic", "nopass", "pass",
        "allocate", "deallocate", "nullify",
        "open", "close", "read", "write", "print", "rewind",
        "backspace", "endfile", "flush", "inquire",
        "external", "intrinsic",
        "pure", "elemental", "recursive", "impure",
        "bind",
        ".true.", ".false.",
        ".and.", ".or.", ".not.", ".eqv.", ".neqv.",
        ".eq.", ".ne.", ".lt.", ".le.", ".gt.", ".ge.",
    },
    keywords3  = {
        "abs", "acos", "acosh", "asin", "asinh", "atan", "atan2", "atanh",
        "ceiling", "cmplx", "conjg", "cos", "cosh", "dble",
        "exp", "floor", "huge", "int", "log", "log10",
        "max", "maxval", "min", "minval", "mod", "modulo",
        "nint", "real", "sign", "sin", "sinh",
        "sqrt", "tan", "tanh", "tiny",
        "len", "len_trim", "trim", "adjustl", "adjustr",
        "index", "scan", "verify", "repeat",
        "achar", "char", "iachar", "ichar",
        "allocated", "associated", "present", "size", "shape",
        "rank", "lbound", "ubound",
        "sum", "product", "count", "any", "all",
        "matmul", "dot_product", "transpose",
        "reshape", "spread", "pack", "unpack", "merge",
        "selected_int_kind", "selected_real_kind", "kind",
        "digits", "epsilon", "maxexponent", "minexponent",
        "precision", "radix", "range",
        "new_line", "c_null_char", "c_new_line",
    },
})
