-- GDScript syntax definition (Godot Engine)
lex.define_syntax({
    name       = "GDScript",
    extensions = { ".gd" },
    comment    = "#",
    keywords1  = {
        "if", "elif", "else", "for", "while", "match",
        "break", "continue", "pass", "return",
        "and", "or", "not", "in", "is",
        "await",
    },
    keywords2  = {
        "class", "class_name", "extends", "func", "static",
        "var", "const", "enum",
        "export", "onready", "signal",
        "tool", "yield",
        "self", "super",
        "true", "false", "null",
        "INF", "NAN", "PI", "TAU",
        "@export", "@onready", "@tool",
        "@warning_ignore", "@static_unload",
    },
    keywords3  = {
        "int", "float", "bool", "String", "StringName",
        "NodePath", "Array", "Dictionary", "Object",
        "Vector2", "Vector2i", "Vector3", "Vector3i",
        "Vector4", "Vector4i",
        "Rect2", "Rect2i",
        "Transform2D", "Transform3D",
        "Basis", "Quaternion", "Plane",
        "Color", "AABB",
        "Callable", "Signal", "RID",
        "PackedByteArray", "PackedInt32Array",
        "PackedInt64Array", "PackedFloat32Array",
        "PackedFloat64Array", "PackedStringArray",
        "PackedVector2Array", "PackedVector3Array",
        "PackedColorArray",
        "Node", "Node2D", "Node3D",
        "Control", "CanvasItem",
        "Resource", "RefCounted",
        "print", "printerr", "printraw",
        "push_warning", "push_error",
        "len", "range", "abs", "ceil", "floor",
        "round", "clamp", "lerp", "min", "max",
        "sign", "sqrt", "pow", "log", "exp",
        "sin", "cos", "tan", "asin", "acos", "atan", "atan2",
        "deg_to_rad", "rad_to_deg",
        "typeof", "str", "int", "float", "bool",
        "is_instance_valid", "weakref",
    },
})
