-- GLSL syntax definition
lex.define_syntax({
    name       = "GLSL",
    extensions = { ".glsl", ".vert", ".frag", ".geom", ".comp",
                   ".tesc", ".tese", ".mesh", ".task", ".rgen",
                   ".rint", ".rahit", ".rchit", ".rmiss", ".rcall" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "break", "case", "continue", "default", "discard",
        "do", "else", "for", "if", "return", "switch", "while",
    },
    keywords2  = {
        "attribute", "buffer", "centroid", "coherent",
        "const", "flat", "highp", "in", "inout",
        "invariant", "layout", "lowp", "mediump",
        "noperspective", "out", "patch", "precision",
        "readonly", "restrict", "sample", "shared",
        "smooth", "struct", "subroutine", "uniform",
        "varying", "volatile", "writeonly",
        "true", "false",
        "#version", "#extension", "#define", "#undef",
        "#if", "#ifdef", "#ifndef", "#else", "#elif",
        "#endif", "#pragma", "#line", "#include",
    },
    keywords3  = {
        -- scalar
        "bool", "int", "uint", "float", "double",
        -- vec
        "bvec2", "bvec3", "bvec4",
        "ivec2", "ivec3", "ivec4",
        "uvec2", "uvec3", "uvec4",
        "vec2", "vec3", "vec4",
        "dvec2", "dvec3", "dvec4",
        -- mat
        "mat2", "mat3", "mat4",
        "mat2x2", "mat2x3", "mat2x4",
        "mat3x2", "mat3x3", "mat3x4",
        "mat4x2", "mat4x3", "mat4x4",
        "dmat2", "dmat3", "dmat4",
        -- samplers
        "sampler1D", "sampler2D", "sampler3D",
        "samplerCube", "sampler2DRect",
        "sampler1DArray", "sampler2DArray",
        "samplerCubeArray", "samplerBuffer",
        "sampler2DMS", "sampler2DMSArray",
        "sampler1DShadow", "sampler2DShadow",
        "samplerCubeShadow",
        "isampler2D", "usampler2D",
        -- images
        "image1D", "image2D", "image3D",
        "imageCube", "image2DRect",
        -- atomic
        "atomic_uint",
        -- built-in vars
        "gl_Position", "gl_PointSize", "gl_FragCoord",
        "gl_FragDepth", "gl_FrontFacing", "gl_PointCoord",
        "gl_VertexID", "gl_InstanceID", "gl_DrawID",
        "gl_BaseVertex", "gl_BaseInstance",
        "gl_Layer", "gl_ViewportIndex",
        "gl_GlobalInvocationID", "gl_LocalInvocationID",
        "gl_WorkGroupID", "gl_WorkGroupSize",
        "gl_NumWorkGroups", "gl_LocalInvocationIndex",
        -- built-in funcs
        "abs", "acos", "acosh", "all", "any",
        "asin", "asinh", "atan", "atanh",
        "ceil", "clamp", "cos", "cosh", "cross",
        "degrees", "dFdx", "dFdy", "distance",
        "dot", "emit", "equal", "exp", "exp2",
        "faceforward", "floor", "fract", "fma",
        "fwidth", "greaterThan", "greaterThanEqual",
        "imageLoad", "imageStore", "imageAtomicAdd",
        "intBitsToFloat", "inverse", "inversesqrt",
        "isinf", "isnan", "length", "lessThan",
        "lessThanEqual", "log", "log2", "matrixCompMult",
        "max", "min", "mix", "mod", "modf",
        "noise", "normalize", "not", "notEqual",
        "outerProduct", "packHalf2x16", "packUnorm2x16",
        "pow", "radians", "reflect", "refract",
        "round", "roundEven", "sign", "sin", "sinh",
        "smoothstep", "sqrt", "step", "tan", "tanh",
        "texelFetch", "texture", "textureGather",
        "textureGrad", "textureLod", "textureOffset",
        "textureProj", "textureSize",
        "transpose", "trunc", "uintBitsToFloat",
        "unpackHalf2x16", "unpackUnorm2x16",
    },
})
