-- HLSL syntax definition
lex.define_syntax({
    name       = "HLSL",
    extensions = { ".hlsl", ".hlsli", ".fx", ".fxh", ".vsh", ".psh", ".csh" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "break", "case", "continue", "default", "discard",
        "do", "else", "for", "if", "return", "switch", "while",
    },
    keywords2  = {
        "AppendStructuredBuffer", "asm", "asm_fragment",
        "BlendState", "Buffer", "ByteAddressBuffer",
        "cbuffer", "centroid", "class", "column_major",
        "compile_fragment", "CompileShader", "const",
        "continue", "ComputeShader",
        "ConsumeStructuredBuffer", "DepthStencilState",
        "DepthStencilView", "domainshader", "dword",
        "export", "extern", "false", "fxgroup", "geometry",
        "groupshared", "hull", "indices", "in", "inline",
        "inout", "InputPatch", "interface", "line",
        "lineadj", "linear", "LineStream", "matrix",
        "namespace", "nointerpolation", "noperspective",
        "NULL", "out", "OutputPatch", "packoffset",
        "pass", "payload", "pixelfragment", "PixelShader",
        "point", "PointStream", "precise", "RasterizerState",
        "RenderTargetView", "register", "return",
        "RWBuffer", "RWByteAddressBuffer", "RWStructuredBuffer",
        "RWTexture1D", "RWTexture1DArray", "RWTexture2D",
        "RWTexture2DArray", "RWTexture3D",
        "sample", "sampler", "SamplerComparisonState",
        "SamplerState", "shared", "snorm",
        "stateblock", "stateblock_state", "static",
        "string", "struct", "switch", "tbuffer",
        "technique", "technique10", "technique11",
        "texture", "Texture1D", "Texture1DArray",
        "Texture2D", "Texture2DArray", "Texture2DMS",
        "Texture2DMSArray", "Texture3D", "TextureCube",
        "TextureCubeArray",
        "triangle", "triangleadj", "TriangleStream",
        "true", "typedef", "uniform", "unorm",
        "unsigned", "vector", "vertexfragment",
        "VertexShader", "volatile",
        "#define", "#include", "#pragma", "#if", "#ifdef",
        "#ifndef", "#else", "#elif", "#endif",
    },
    keywords3  = {
        -- scalars
        "bool", "int", "uint", "half", "float", "double",
        "min16float", "min10float", "min16int", "min12int",
        "min16uint",
        -- vectors
        "bool1", "bool2", "bool3", "bool4",
        "int1", "int2", "int3", "int4",
        "uint1", "uint2", "uint3", "uint4",
        "half1", "half2", "half3", "half4",
        "float1", "float2", "float3", "float4",
        "double1", "double2", "double3", "double4",
        -- matrices
        "float1x1", "float1x2", "float1x3", "float1x4",
        "float2x1", "float2x2", "float2x3", "float2x4",
        "float3x1", "float3x2", "float3x3", "float3x4",
        "float4x1", "float4x2", "float4x3", "float4x4",
        "int2x2", "int3x3", "int4x4",
        "uint2x2", "uint3x3", "uint4x4",
        -- semantics
        "POSITION", "NORMAL", "TEXCOORD", "COLOR",
        "BINORMAL", "TANGENT", "BLENDWEIGHT", "BLENDINDICES",
        "SV_Position", "SV_Target", "SV_Depth",
        "SV_VertexID", "SV_InstanceID",
        "SV_DispatchThreadID", "SV_GroupID",
        "SV_GroupThreadID", "SV_GroupIndex",
        "SV_IsFrontFace", "SV_SampleIndex",
        -- intrinsics
        "abs", "acos", "all", "any", "asfloat", "asin",
        "asint", "asuint", "atan", "atan2", "ceil",
        "clamp", "clip", "cos", "cosh", "cross",
        "D3DCOLORtoUBYTE4", "ddx", "ddx_coarse", "ddx_fine",
        "ddy", "ddy_coarse", "ddy_fine", "degrees",
        "determinant", "distance", "dot", "dst",
        "errorf", "exp", "exp2", "f16tof32", "f32tof16",
        "faceforward", "firstbithigh", "firstbitlow",
        "floor", "fma", "fmod", "frac", "frexp",
        "fwidth", "GetRenderTargetSampleCount",
        "GetRenderTargetSamplePosition",
        "InterlockedAdd", "InterlockedAnd",
        "InterlockedCompareExchange",
        "InterlockedExchange", "InterlockedMax",
        "InterlockedMin", "InterlockedOr", "InterlockedXor",
        "isfinite", "isinf", "isnan",
        "ldexp", "length", "lerp", "lit", "log", "log10",
        "log2", "mad", "max", "min", "modf", "msad4",
        "mul", "normalize", "pow", "printf",
        "Process2DQuadTessFactorsAvg",
        "radians", "rcp", "reflect", "refract",
        "reversebits", "round", "rsqrt", "saturate",
        "sign", "sin", "sincos", "sinh", "smoothstep",
        "sqrt", "step", "tan", "tanh", "tex1D", "tex2D",
        "tex3D", "texCUBE", "transpose", "trunc",
    },
})
