-- Kotlin syntax definition
lex.define_syntax({
    name       = "Kotlin",
    extensions = { ".kt", ".kts" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "break", "continue", "do", "else", "for", "if",
        "in", "return", "throw", "try", "catch", "finally",
        "when", "while", "as", "is",
    },
    keywords2  = {
        "abstract", "actual", "annotation", "by", "class", "companion",
        "const", "constructor", "crossinline", "data", "delegate",
        "dynamic", "enum", "expect", "external",
        "field", "file", "final", "fun", "get", "import",
        "infix", "init", "inline", "inner", "interface",
        "internal", "it", "lateinit", "noinline", "null",
        "object", "open", "operator", "out", "override",
        "package", "param", "private", "property", "protected",
        "public", "receiver", "reified", "sealed",
        "set", "setparam", "super", "suspend", "tailrec",
        "this", "true", "false", "typealias", "typeof",
        "val", "value", "var", "vararg", "where",
    },
    keywords3  = {
        "Any", "Boolean", "Byte", "Char", "Double", "Float",
        "Int", "Long", "Nothing", "Number", "Short", "String",
        "Unit",
        "Array", "IntArray", "LongArray", "FloatArray",
        "DoubleArray", "BooleanArray", "ByteArray", "CharArray",
        "List", "MutableList", "Map", "MutableMap",
        "Set", "MutableSet", "Pair", "Triple",
        "Sequence", "Iterable", "Collection",
        "Comparable", "Comparator",
        "Exception", "RuntimeException", "IllegalArgumentException",
        "IllegalStateException", "IndexOutOfBoundsException",
        "NullPointerException", "UnsupportedOperationException",
        "println", "print", "readLine",
        "also", "apply", "let", "run", "with",
        "lazy", "listOf", "mutableListOf", "mapOf", "mutableMapOf",
        "setOf", "mutableSetOf", "arrayOf", "emptyList",
    },
})
