-- NASM (Netwide Assembler) syntax definition
lex.define_syntax({
    name       = "NASM",
    extensions = { ".asm", ".nasm", ".s", ".S" },
    comment    = ";",
    keywords1  = {
        -- control flow
        "jmp", "je", "jne", "jz", "jnz", "jg", "jge", "jl", "jle",
        "ja", "jae", "jb", "jbe", "jo", "jno", "js", "jns", "jcxz",
        "jecxz", "jrcxz", "loop", "loope", "loopne", "loopnz", "loopz",
        "call", "ret", "retn", "retf", "iret", "iretd", "iretq",
        "enter", "leave",
    },
    keywords2  = {
        -- instructions
        "mov", "movsx", "movzx", "movs", "movsb", "movsw", "movsd", "movsq",
        "push", "pop", "pusha", "popa", "pushad", "popad", "pushf", "popf",
        "lea", "xchg", "xadd", "cmpxchg", "bswap",
        "add", "sub", "mul", "imul", "div", "idiv", "inc", "dec",
        "neg", "adc", "sbb",
        "and", "or", "xor", "not", "shl", "shr", "sal", "sar",
        "rol", "ror", "rcl", "rcr", "shld", "shrd",
        "cmp", "test", "bt", "bts", "btr", "btc", "bsf", "bsr",
        "nop", "hlt", "cli", "sti", "cld", "std", "clc", "stc", "cmc",
        "int", "syscall", "sysenter", "sysexit", "cpuid", "rdtsc",
        "rep", "repe", "repne", "repz", "repnz",
        "lods", "lodsb", "lodsw", "lodsd", "lodsq",
        "stos", "stosb", "stosw", "stosd", "stosq",
        "scas", "scasb", "scasw", "scasd", "scasq",
        "cmps", "cmpsb", "cmpsw", "cmpsd", "cmpsq",
        "in", "out", "ins", "outs",
        "cbw", "cwd", "cwde", "cdq", "cdqe", "cqo",
        "setg", "setge", "setl", "setle", "sete", "setne",
        "seta", "setae", "setb", "setbe",
    },
    keywords3  = {
        -- registers
        "rax", "rbx", "rcx", "rdx", "rsi", "rdi", "rsp", "rbp",
        "r8",  "r9",  "r10", "r11", "r12", "r13", "r14", "r15",
        "eax", "ebx", "ecx", "edx", "esi", "edi", "esp", "ebp",
        "r8d", "r9d", "r10d","r11d","r12d","r13d","r14d","r15d",
        "ax",  "bx",  "cx",  "dx",  "si",  "di",  "sp",  "bp",
        "al",  "bl",  "cl",  "dl",  "ah",  "bh",  "ch",  "dh",
        "sil", "dil", "spl", "bpl",
        "cs",  "ds",  "es",  "fs",  "gs",  "ss",
        "rip", "eip", "ip",
        "xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7",
        "xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15",
        "ymm0","ymm1","ymm2","ymm3","ymm4","ymm5","ymm6","ymm7",
        "mm0", "mm1", "mm2", "mm3", "mm4", "mm5", "mm6", "mm7",
        "st0", "st1", "st2", "st3", "st4", "st5", "st6", "st7",
        -- directives
        "section", "segment", "global", "extern", "bits", "use16", "use32", "use64",
        "db", "dw", "dd", "dq", "dt", "ddq", "do",
        "resb", "resw", "resd", "resq", "rest", "resdq", "reso",
        "equ", "times", "align", "alignb",
        "byte", "word", "dword", "qword", "tword", "oword", "yword",
        "org", "incbin", "struc", "endstruc", "istruc", "iend",
        "macro", "endmacro", "endm", "local", "rotate",
        "%define", "%undef", "%ifdef", "%ifndef", "%if", "%elif",
        "%else", "%endif", "%include", "%macro", "%endmacro",
        "%rep", "%endrep", "%assign", "%imacro",
    },
})
