-- Nim syntax definition
lex.define_syntax({
    name       = "Nim",
    extensions = { ".nim", ".nims", ".nimble" },
    comment    = "#",
    multiline_comment = { "#[", "]#" },
    keywords1  = {
        "addr", "and", "as", "asm", "bind", "block",
        "break", "case", "cast", "concept", "const",
        "continue", "converter", "defer", "discard",
        "distinct", "div", "do", "elif", "else", "end",
        "enum", "except", "export", "finally", "for",
        "from", "func", "if", "import", "in", "include",
        "interface", "is", "isnot", "iterator", "let",
        "macro", "method", "mixin", "mod", "nil",
        "not", "notin", "object", "of", "or", "out",
        "proc", "ptr", "raise", "ref", "return",
        "shl", "shr", "static", "template", "try",
        "tuple", "type", "using", "var", "when",
        "while", "with", "without", "xor", "yield",
    },
    keywords2  = {
        "true", "false",
        "and", "or", "not",
        "sizeof", "typeof",
        "result",
        "generic",
    },
    keywords3  = {
        "bool", "byte", "char", "cint", "clong", "csize_t",
        "cstring", "cuint", "float", "float32", "float64",
        "int", "int8", "int16", "int32", "int64",
        "Natural", "Positive",
        "string", "uint", "uint8", "uint16", "uint32", "uint64",
        "seq", "array", "set", "openArray", "varargs",
        "void", "auto",
        "Ordinal", "range",
        "echo", "write", "writeLine", "readLine",
        "newSeq", "newString", "len", "high", "low",
        "inc", "dec", "succ", "pred",
        "add", "del", "delete", "insert", "contains",
        "repr", "toHex",
        "Exception", "IOError", "ValueError", "KeyError",
        "IndexError", "FieldError", "OutOfMemError",
        "OSError", "OverflowDefect", "DivByZeroDefect",
        "assert", "doAssert", "quit",
    },
})
