-- Odin syntax definition
lex.define_syntax({
    name       = "Odin",
    extensions = { ".odin" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "if", "else", "for", "switch", "case",
        "break", "continue", "fallthrough", "return",
        "defer", "when",
        "do",
    },
    keywords2  = {
        "import", "package", "foreign",
        "proc", "struct", "union", "enum", "bit_set", "map",
        "using", "distinct", "dynamic",
        "const", "var",
        "in", "not_in",
        "cast", "transmute", "auto_cast",
        "or_else", "or_return",
        "nil", "true", "false",
        "asm",
        "context",
    },
    keywords3  = {
        "bool", "b8", "b16", "b32", "b64",
        "int", "uint", "uintptr",
        "i8", "i16", "i32", "i64", "i128",
        "u8", "u16", "u32", "u64", "u128",
        "i16le", "i32le", "i64le", "i128le",
        "u16le", "u32le", "u64le", "u128le",
        "i16be", "i32be", "i64be", "i128be",
        "u16be", "u32be", "u64be", "u128be",
        "f16", "f32", "f64",
        "f16le", "f32le", "f64le",
        "f16be", "f32be", "f64be",
        "complex32", "complex64", "complex128",
        "quaternion64", "quaternion128", "quaternion256",
        "rune", "string", "cstring", "rawptr",
        "typeid", "any",
        "byte",
        "len", "cap", "size_of", "align_of", "offset_of",
        "type_of", "typeid_of",
        "make", "new", "free", "delete", "append", "clear",
        "reserve", "resize", "copy", "pop",
        "min", "max", "abs", "clamp",
        "print", "println", "printf", "eprintln", "eprintf",
        "panic", "assert",
    },
})
