-- Perl syntax definition
lex.define_syntax({
    name       = "Perl",
    extensions = { ".pl", ".pm", ".pod", ".t" },
    comment    = "#",
    keywords1  = {
        "if", "elsif", "else", "unless",
        "for", "foreach", "while", "until", "do",
        "last", "next", "redo", "return",
        "given", "when", "default",
        "and", "or", "not",
    },
    keywords2  = {
        "BEGIN", "END", "INIT", "CHECK", "UNITCHECK",
        "package", "use", "no", "require",
        "sub", "my", "our", "local", "state",
        "bless", "ref", "tied", "tie", "untie",
        "eval", "die", "warn",
        "defined", "undef", "exists", "delete",
        "wantarray", "caller",
        "import", "DESTROY", "AUTOLOAD",
        "strict", "warnings",
        "true", "false",
    },
    keywords3  = {
        "print", "say", "printf", "sprintf", "readline",
        "chomp", "chop", "chr", "ord",
        "length", "substr", "index", "rindex",
        "uc", "lc", "ucfirst", "lcfirst",
        "split", "join", "reverse", "sort",
        "push", "pop", "shift", "unshift", "splice",
        "keys", "values", "each", "delete", "exists",
        "map", "grep", "wantarray",
        "open", "close", "read", "write",
        "eof", "seek", "tell", "truncate",
        "stat", "lstat", "rename", "unlink", "mkdir",
        "opendir", "readdir", "closedir",
        "system", "exec", "fork", "wait",
        "int", "abs", "sqrt", "exp", "log",
        "sin", "cos", "atan2", "rand", "srand",
        "hex", "oct", "sprintf",
        "ref", "scalar",
        "STDIN", "STDOUT", "STDERR",
        "UNIVERSAL", "POSIX", "Scalar::Util", "List::Util",
        "Carp", "Data::Dumper", "Storable",
        "File::Basename", "File::Path", "File::Find",
        "Cwd", "Getopt::Long",
    },
})
