-- PHP syntax definition
lex.define_syntax({
    name       = "PHP",
    extensions = { ".php", ".php3", ".php4", ".php5", ".php8", ".phtml" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "break", "case", "catch", "continue", "default", "do",
        "else", "elseif", "endfor", "endforeach", "endif",
        "endswitch", "endwhile", "finally", "for", "foreach",
        "goto", "if", "match", "return", "switch", "throw",
        "try", "while", "yield", "yield from",
    },
    keywords2  = {
        "abstract", "array", "as", "callable", "class", "clone",
        "const", "declare", "echo", "empty", "enum", "eval",
        "exit", "extends", "final", "fn", "function", "global",
        "implements", "include", "include_once", "instanceof",
        "insteadof", "interface", "isset", "list", "match",
        "namespace", "new", "print", "private", "protected",
        "public", "readonly", "require", "require_once",
        "static", "trait", "unset", "use", "var",
        "true", "false", "null",
        "TRUE", "FALSE", "NULL",
        "__CLASS__", "__DIR__", "__FILE__", "__FUNCTION__",
        "__LINE__", "__METHOD__", "__NAMESPACE__", "__TRAIT__",
    },
    keywords3  = {
        "int", "float", "string", "bool", "void",
        "array", "object", "callable", "iterable",
        "mixed", "never", "self", "parent", "static",
        "Exception", "RuntimeException", "LogicException",
        "InvalidArgumentException", "TypeError",
        "ValueError", "Error", "Throwable",
        "ArrayAccess", "Countable", "Iterator",
        "Traversable", "Stringable",
        "stdClass", "DateTime", "DateTimeImmutable",
        "Closure", "Generator",
        "array_map", "array_filter", "array_reduce",
        "array_keys", "array_values", "array_merge",
        "array_push", "array_pop", "array_shift",
        "count", "strlen", "str_len", "substr",
        "str_replace", "str_contains", "str_starts_with",
        "str_ends_with", "trim", "ltrim", "rtrim",
        "explode", "implode", "sprintf", "printf",
        "var_dump", "var_export",
        "is_array", "is_string", "is_int", "is_float",
        "is_bool", "is_null", "is_object",
        "intval", "floatval", "strval", "boolval",
        "json_encode", "json_decode",
    },
})
