-- R syntax definition
lex.define_syntax({
    name       = "R",
    extensions = { ".r", ".R", ".Rmd", ".Rnw" },
    comment    = "#",
    keywords1  = {
        "if", "else", "for", "while", "repeat",
        "break", "next", "return",
        "in",
    },
    keywords2  = {
        "function", "lambda",
        "TRUE", "FALSE", "NULL", "NA", "Inf", "NaN",
        "NA_integer_", "NA_real_", "NA_complex_", "NA_character_",
        "T", "F",
        "...", "..", ".",
    },
    keywords3  = {
        "print", "cat", "message", "warning", "stop",
        "paste", "paste0", "sprintf", "format",
        "nchar", "substring", "sub", "gsub", "grep", "grepl",
        "toupper", "tolower", "trimws",
        "c", "list", "vector", "array", "matrix",
        "data.frame", "tibble",
        "length", "nrow", "ncol", "dim",
        "seq", "seq_len", "seq_along", "rep",
        "which", "match", "order", "sort", "rank",
        "sum", "prod", "cumsum", "cumprod",
        "mean", "median", "var", "sd", "range",
        "min", "max", "abs", "sqrt", "exp", "log", "log10",
        "ceiling", "floor", "round", "trunc",
        "is.na", "is.null", "is.finite", "is.infinite",
        "is.numeric", "is.character", "is.logical",
        "is.vector", "is.list", "is.data.frame",
        "as.numeric", "as.character", "as.logical",
        "as.integer", "as.factor", "as.data.frame",
        "apply", "lapply", "sapply", "vapply",
        "tapply", "mapply", "Map", "Reduce", "Filter",
        "do.call", "Recall",
        "library", "require", "install.packages",
        "source", "setwd", "getwd",
        "read.csv", "read.table", "readRDS", "readLines",
        "write.csv", "write.table", "saveRDS", "writeLines",
        "Sys.time", "Sys.sleep", "Sys.getenv",
        "class", "typeof", "mode", "str", "summary",
        "head", "tail", "subset",
        "merge", "reshape", "aggregate",
        "plot", "hist", "boxplot", "barplot", "pie",
        "ggplot",
    },
})
