-- Scala syntax definition
lex.define_syntax({
    name       = "Scala",
    extensions = { ".scala", ".sc", ".sbt" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "case", "catch", "do", "else", "finally", "for",
        "forSome", "if", "in", "match", "return", "throw",
        "try", "while", "yield",
    },
    keywords2  = {
        "abstract", "class", "def", "enum", "export",
        "extends", "final", "given", "implicit", "import",
        "inline", "lazy", "new", "object", "opaque",
        "open", "override", "package", "private", "protected",
        "sealed", "super", "this", "trait", "transparent",
        "type", "using", "val", "var", "with",
        "null", "true", "false",
        "derives", "end",
    },
    keywords3  = {
        "Any", "AnyRef", "AnyVal", "Boolean", "Byte",
        "Char", "Double", "Float", "Int", "Long",
        "Nothing", "Null", "Short", "String", "Unit",
        "Option", "Some", "None",
        "Either", "Left", "Right",
        "Try", "Success", "Failure",
        "Future", "Promise",
        "List", "Seq", "Vector", "Array", "Set", "Map",
        "Iterable", "Iterator", "Range",
        "Tuple2", "Tuple3",
        "Function0", "Function1", "Function2",
        "PartialFunction",
        "Product", "Serializable",
        "Comparable", "Ordering",
        "Exception", "RuntimeException",
        "println", "print", "printf",
        "classOf", "isInstanceOf", "asInstanceOf",
    },
})
