-- SQL syntax definition
lex.define_syntax({
    name       = "SQL",
    extensions = { ".sql", ".ddl", ".dml" },
    comment    = "--",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "SELECT", "FROM", "WHERE", "AND", "OR", "NOT", "IN",
        "BETWEEN", "LIKE", "IS", "NULL", "EXISTS",
        "JOIN", "INNER", "LEFT", "RIGHT", "FULL", "OUTER", "CROSS",
        "ON", "USING",
        "GROUP", "BY", "HAVING", "ORDER", "ASC", "DESC",
        "LIMIT", "OFFSET", "FETCH", "FIRST", "NEXT", "ROWS", "ONLY",
        "UNION", "INTERSECT", "EXCEPT", "ALL", "DISTINCT",
        "INSERT", "INTO", "VALUES", "UPDATE", "SET",
        "DELETE", "TRUNCATE", "MERGE",
        "CASE", "WHEN", "THEN", "ELSE", "END",
        "WITH", "AS", "RECURSIVE",
        "select", "from", "where", "and", "or", "not", "in",
        "between", "like", "is", "null", "exists",
        "join", "inner", "left", "right", "full", "outer", "cross",
        "on", "using",
        "group", "by", "having", "order", "asc", "desc",
        "limit", "offset",
        "union", "intersect", "except", "all", "distinct",
        "insert", "into", "values", "update", "set",
        "delete", "truncate", "merge",
        "case", "when", "then", "else", "end",
        "with", "as", "recursive",
    },
    keywords2  = {
        "CREATE", "ALTER", "DROP", "TABLE", "INDEX", "VIEW", "DATABASE",
        "SCHEMA", "SEQUENCE", "PROCEDURE", "FUNCTION", "TRIGGER",
        "CONSTRAINT", "PRIMARY", "FOREIGN", "KEY", "UNIQUE",
        "REFERENCES", "CHECK", "DEFAULT", "NOT NULL",
        "GRANT", "REVOKE", "COMMIT", "ROLLBACK", "SAVEPOINT",
        "BEGIN", "TRANSACTION",
        "create", "alter", "drop", "table", "index", "view", "database",
        "schema", "sequence", "procedure", "function", "trigger",
        "constraint", "primary", "foreign", "key", "unique",
        "references", "check", "default",
        "grant", "revoke", "commit", "rollback", "savepoint",
        "begin", "transaction",
        "IF", "THEN", "ELSIF", "LOOP", "RETURN", "DECLARE",
        "if", "then", "elsif", "loop", "return", "declare",
    },
    keywords3  = {
        "INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT",
        "FLOAT", "DOUBLE", "REAL", "NUMERIC", "DECIMAL",
        "CHAR", "VARCHAR", "TEXT", "CLOB",
        "BINARY", "VARBINARY", "BLOB",
        "BOOLEAN", "BOOL", "BIT",
        "DATE", "TIME", "TIMESTAMP", "DATETIME", "INTERVAL",
        "JSON", "JSONB", "XML", "UUID",
        "SERIAL", "BIGSERIAL",
        "int", "integer", "bigint", "smallint",
        "float", "double", "real", "numeric", "decimal",
        "char", "varchar", "text",
        "boolean", "bool",
        "date", "time", "timestamp", "datetime",
        "json", "jsonb", "xml", "uuid",
        "COUNT", "SUM", "AVG", "MIN", "MAX",
        "COALESCE", "NULLIF", "NVL", "IIF",
        "CAST", "CONVERT",
        "NOW", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP",
        "count", "sum", "avg", "min", "max",
        "coalesce", "nullif",
        "cast", "convert",
        "now", "current_date", "current_time", "current_timestamp",
    },
    flags = 3,
})
