-- Swift syntax definition
lex.define_syntax({
    name       = "Swift",
    extensions = { ".swift" },
    comment    = "//",
    multiline_comment = { "/*", "*/" },
    keywords1  = {
        "break", "case", "catch", "continue", "default", "defer",
        "do", "else", "fallthrough", "for", "guard", "if",
        "in", "repeat", "return", "switch", "throw",
        "try", "where", "while", "await",
    },
    keywords2  = {
        "Any", "AnyObject", "as", "async", "associatedtype",
        "class", "convenience", "deinit", "didSet",
        "dynamic", "enum", "extension", "fileprivate", "final",
        "func", "get", "import", "indirect", "infix", "init",
        "inout", "internal", "is", "isolated", "lazy", "let",
        "mutating", "nil", "nonisolated", "nonmutating",
        "open", "operator", "optional", "override", "postfix",
        "precedencegroup", "prefix", "private", "protocol",
        "public", "rethrows", "self", "Self", "set",
        "some", "static", "struct", "subscript", "super",
        "throws", "true", "false", "Type", "typealias",
        "unowned", "var", "weak", "willSet",
        "_", "actor", "distributed", "package", "macro",
    },
    keywords3  = {
        "Bool", "Character", "Double", "Float",
        "Float16", "Float32", "Float64",
        "Int", "Int8", "Int16", "Int32", "Int64",
        "UInt", "UInt8", "UInt16", "UInt32", "UInt64",
        "String", "Substring", "Unicode",
        "Array", "ContiguousArray", "ArraySlice",
        "Dictionary", "Set",
        "Optional", "Result", "Never",
        "Error", "LocalizedError",
        "Codable", "Encodable", "Decodable",
        "Comparable", "Equatable", "Hashable",
        "Sequence", "Collection", "IteratorProtocol",
        "RandomAccessCollection", "MutableCollection",
        "Identifiable",
        "print", "fatalError", "precondition", "assert",
        "zip", "stride", "min", "max", "abs",
    },
})
