-- Tcl syntax definition
lex.define_syntax({
    name       = "Tcl",
    extensions = { ".tcl", ".tk", ".itcl", ".itk", ".tm" },
    comment    = "#",
    keywords1  = {
        "if", "elseif", "else",
        "for", "foreach", "while", "loop",
        "break", "continue", "return",
        "switch", "case",
        "try", "catch", "throw",
        "error",
    },
    keywords2  = {
        "proc", "namespace", "package", "class", "method",
        "set", "unset", "variable", "global", "upvar",
        "expr", "incr", "append", "lappend",
        "eval", "uplevel", "subst", "apply",
        "rename", "source", "load", "unload",
        "puts", "gets", "read", "open", "close", "flush",
        "eof", "seek", "tell", "fconfigure",
        "cd", "pwd", "glob", "file",
        "exec", "pid", "exit",
        "after", "update", "vwait",
        "trace", "interp",
        "tailcall",
        "true", "false",
    },
    keywords3  = {
        "list", "lindex", "llength", "lrange", "lreplace",
        "linsert", "lsearch", "lsort", "lreverse", "lmap",
        "join", "split", "concat",
        "string", "format", "scan",
        "regexp", "regsub",
        "dict", "array", "info",
        "clock", "binary", "encoding",
        "http", "socket", "fcopy",
        "chan", "coroutine", "yield", "yieldto",
        "oo::class", "oo::object", "my",
        "self", "next",
        "tk", "button", "label", "entry", "frame",
        "canvas", "listbox", "menu", "text", "scale",
        "scrollbar", "pack", "grid", "place",
        "bind", "event", "winfo", "wm",
    },
})
