-- WGSL (WebGPU Shading Language) syntax definition
lex.define_syntax({
    name       = "WGSL",
    extensions = { ".wgsl" },
    comment    = "//",
    keywords1  = {
        "break", "case", "continue", "continuing", "default",
        "discard", "else", "for", "if", "loop",
        "return", "switch", "while",
    },
    keywords2  = {
        "alias", "const", "const_assert",
        "diagnostic", "enable", "requires",
        "fn", "let", "override", "struct", "var",
        "in", "out",
        "true", "false",
        "@binding", "@builtin", "@compute",
        "@const", "@diagnostic",
        "@fragment", "@group", "@id",
        "@interpolate", "@invariant", "@location",
        "@must_use", "@size", "@align",
        "@vertex", "@workgroup_size",
        "read", "write", "read_write",
        "function", "private", "storage",
        "uniform", "workgroup",
    },
    keywords3  = {
        -- scalars
        "bool", "f16", "f32", "f64",
        "i32", "u32", "i64", "u64",
        "abstractInt", "abstractFloat",
        -- vectors
        "vec2", "vec3", "vec4",
        "vec2i", "vec3i", "vec4i",
        "vec2u", "vec3u", "vec4u",
        "vec2f", "vec3f", "vec4f",
        "vec2h", "vec3h", "vec4h",
        -- matrices
        "mat2x2f", "mat2x3f", "mat2x4f",
        "mat3x2f", "mat3x3f", "mat3x4f",
        "mat4x2f", "mat4x3f", "mat4x4f",
        -- textures
        "texture_1d", "texture_2d", "texture_3d",
        "texture_cube", "texture_2d_array", "texture_cube_array",
        "texture_multisampled_2d",
        "texture_storage_1d", "texture_storage_2d",
        "texture_storage_2d_array", "texture_storage_3d",
        "texture_depth_2d", "texture_depth_2d_array",
        "texture_depth_cube", "texture_depth_cube_array",
        "texture_depth_multisampled_2d",
        -- samplers
        "sampler", "sampler_comparison",
        -- atomics
        "atomic",
        -- arrays
        "array",
        -- built-in values
        "vertex_index", "instance_index", "position",
        "front_facing", "frag_depth", "sample_index",
        "sample_mask", "local_invocation_id",
        "local_invocation_index", "global_invocation_id",
        "workgroup_id", "num_workgroups",
        -- built-in funcs
        "abs", "acos", "acosh", "asin", "asinh", "atan", "atanh",
        "atan2", "ceil", "clamp", "cos", "cosh", "countLeadingZeros",
        "countOneBits", "countTrailingZeros", "cross",
        "degrees", "determinant", "distance", "dot",
        "exp", "exp2", "extractBits", "faceForward",
        "firstLeadingBit", "firstTrailingBit",
        "floor", "fma", "fract", "frexp",
        "insertBits", "inverseSqrt", "ldexp", "length",
        "log", "log2", "max", "min", "mix", "modf",
        "normalize", "pow", "quantizeToF16",
        "radians", "reflect", "refract",
        "reverseBits", "round", "saturate", "sign",
        "sin", "sinh", "smoothstep", "sqrt", "step",
        "tan", "tanh", "transpose", "trunc",
        "textureDimensions", "textureGather",
        "textureGatherCompare", "textureLoad",
        "textureNumLayers", "textureNumLevels",
        "textureNumSamples", "textureSample",
        "textureSampleBias", "textureSampleCompare",
        "textureSampleCompareLevel", "textureSampleGrad",
        "textureSampleLevel", "textureSampleBaseClampToEdge",
        "textureStore",
        "atomicAdd", "atomicAnd", "atomicCompareExchangeWeak",
        "atomicExchange", "atomicLoad", "atomicMax",
        "atomicMin", "atomicOr", "atomicStore", "atomicSub",
        "atomicXor",
        "arrayLength",
        "storageBarrier", "workgroupBarrier", "workgroupUniformLoad",
    },
})
